### ISSUE TITLE
Add Style to the Views

### ISSUE THREAD

**Issue by PatrickRBailey** [Jopatron/KWFCI#45]
TODO:
- Modal
    - [ ] Custom Class for Edit Modal Vs. New Modal
        - A modal that uses the return PartialView("View") functionality needs different styling
- Nav
    - [ ] Fix Logout Button to go back to previous version
- Login
    - [ ] revert the styling back to how it was previously
- Home Page
    - [ ] Fix Critical Alerts Graphic
